### ISSUE TITLE
Kient integration on NestJS (Error with require() of ES Module)

### ISSUE THREAD

**Issue by sebasnallar** [zSoulweaver/kient#5]
Hey, I've been trying to use the library on NestJS but I get the error above, could you guys help me? 

`Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/sebastiannallar/dyno/kick/kick-service/node_modules/exit-hook/index.js from /Users/sebastiannallar/dyno/kick/kick-service/node_modules/kient/dist/index.cjs not supported.
Instead change the require of index.js in /Users/sebastiannallar/dyno/kick/kick-service/node_modules/kient/dist/index.cjs to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/sebastiannallar/dyno/kick/kick-service/node_modules/kient/dist/index.cjs:181:32)
    at Object.<anonymous> (/Users/sebastiannallar/dyno/kick/kick-service/dist/providers/kick-client/kick-client.service.js:14:17)
    at Object.<anonymous> (/Users/sebastiannallar/dyno/kick/kick-service/dist/app.service.js:14:31)
    at Object.<anonymous> (/Users/sebastiannallar/dyno/kick/kick-service/dist/app.controller.js:14:23)
    at Object.<anonymous> (/Users/sebastiannallar/dyno/kick/kick-service/dist/app.module.js:11:26)
    at Object.<anonymous> (/Users/sebastiannallar/dyno/kick/kick-service/dist/main.js:4:22)`

**Comment by zSoulweaver** [comment]
Hey @sebasnallar,

I've updated Kient to `1.0.1-11` with some cjs build changes. Could you give this a go for me and let me know how it goes?
